web:
    build: .
    links:
      - mongo
    ports:
       - '3001:3000'
    env_file: .env
    environment:
      - NODE_ENV=development
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_DATABASE=${MONGODB_HOST}
      - MONGODB_PASS=${MONGODB_PASS}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27018:27017'
    volumes:
      - /data/mongodb/db:/data/db
